### PR TITLE
Bundle Update

### PR DESCRIPTION
**Pull request by w0lfschild**
This includes most changes that I implemented in cDock v9.
- 10.10 support
- Force dock dark / light / system -- https://github.com/b3ll/DarkDock
- Icon shadows
- Icon reflections
- Better label hiding
- Color fan view icon highlight
- Adjustable corner size
- Show or hide layers

There is the code to use picture backgrounds and indicators that just needs a path to load from.
It's likely that some of this code is not the ideal implementation but it works.
The app would need to be updated to match these changes to the bundle.

### CODE REVIEW

**Comment by mstg** [comment]
Hmm, why would you need fishhook? You can rebind symbols with Opee as well.
The preferences app is not updated at all to match the new settings, full width dock looks a little bit strange (little bit too high). You miss `modck_enabled` from init plist creation.
Overall, I like what you have tried to do, but it needs some cleaning.

**Comment by mstg** [comment]
You can take whatever function you want to implement into cDock, just credit and I am cool with it :)

**Comment by w0lfschild** [comment]
I used fishhook simply because that's the way it was implemented in DarkDock and I'm not exactly sure how the line 

```
rebind_symbols((struct rebinding[1]){{"CFPreferencesCopyAppValue", hax_CFPreferencesCopyAppValue}}, 1);
```

would be accomplished using ZKwhatever. I originally had a comment 

```
// Something tells me I could do this without fishhook if I already have opee/zkwizzle
// Then again I don't really know what's going on here
```

cDock is also not using Opee, just ZKSwizzle. But yes Modck is included in the credits.

**Comment by mstg** [comment]
I could take a look at it sometime, but I think it would be better if we have all the dock modifications in one place. So if you implement Modck(features you want) into cDock, that would be better :)

**Pull request closed without merging**
